# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import kagglehub

# ================= LOAD DATASET =================

path = kagglehub.dataset_download("basilb2s/language-detection")
print("Dataset Path:", path)

files = os.listdir(path)
csv_file = [f for f in files if f.endswith(".csv")][0]

df = pd.read_csv(os.path.join(path, csv_file))

print(df.head())
print("\nLanguages:\n", df["Language"].value_counts())


# ================= CLEANING =================
# IMPORTANT: Don't remove characters!

def clean_text(text):
    return str(text).lower()


df["Text"] = df["Text"].apply(clean_text)


# ================= FEATURES & LABEL =================

X = df["Text"]
y = df["Language"]


# ================= TRAIN TEST SPLIT =================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


# ================= TF-IDF (CHAR LEVEL 🔥) =================

vectorizer = TfidfVectorizer(
    analyzer='char',
    ngram_range=(1, 5)   # powerful range
)

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)


# ================= MODEL (BEST CHOICE 🔥) =================

model = LinearSVC()
model.fit(X_train, y_train)


# ================= PREDICTION =================

y_pred = model.predict(X_test)

print(f"\n🔥 Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


# ================= F1 SCORE GRAPH =================

report = classification_report(y_test, y_pred, output_dict=True)

languages = list(report.keys())[:-3]
f1_scores = [report[lang]["f1-score"] for lang in languages]

plt.figure(figsize=(12, 6))
sns.barplot(x=languages, y=f1_scores)

plt.xticks(rotation=45)
plt.xlabel("Languages")
plt.ylabel("F1-Score")
plt.title("Language-wise Accuracy")
plt.ylim(0, 1)

plt.show()


# ================= CONFUSION MATRIX =================

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(12, 8))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=model.classes_,
    yticklabels=model.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

# ================= LANGUAGE DETECTION FUNCTION =================

def detect_language(text):
    text = clean_text(text)
    text_tfidf = vectorizer.transform([text])
    return model.predict(text_tfidf)[0]


print("\n===== LANGUAGE DETECTION =====")
user_input = input("Enter text: ")

prediction = detect_language(user_input)
print("Detected Language:", prediction)