# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM


# ================= SUMMARIZATION FUNCTION =================

def summarize_text(
    text,
    model_name="facebook/mbart-large-50",
    max_input_length=512,
    max_output_length=150
):
    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

    # Tokenize input
    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=max_input_length,
        truncation=True
    )

    # Generate summary
    summary_ids = model.generate(
        inputs.input_ids,
        max_length=max_output_length,
        num_beams=5,
        early_stopping=True
    )

    # Decode summary
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

    return summary


# ================= USER INPUT =================

text = input("Enter text to summarize:\n")

summary = summarize_text(text)

print("\nGenerated Summary:\n", summary)