# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Install once (run in terminal or notebook)
# pip install transformers sentencepiece

from transformers import MarianMTModel, MarianTokenizer


# ================= TRANSLATION FUNCTION =================

def translate_text(text, src_lang_code, tgt_lang_code):
    model_name = f"Helsinki-NLP/opus-mt-{src_lang_code}-{tgt_lang_code}"

    try:
        # Load model + tokenizer
        tokenizer = MarianTokenizer.from_pretrained(model_name)
        model = MarianMTModel.from_pretrained(model_name)

        # Tokenize input
        inputs = tokenizer(text, return_tensors="pt", padding=True)

        # Generate translation
        translated = model.generate(**inputs)

        # Decode output
        translated_text = tokenizer.decode(translated[0], skip_special_tokens=True)

        return translated_text

    except Exception as e:
        return f"Translation Error: {e}"


# ================= USER INPUT =================

print("🔤 Language Translator (MarianMT)\n")

text_input = input("Enter text:\n> ")
src_lang = input("Source language (e.g., en):\n> ").strip()
tgt_lang = input("Target language (e.g., fr):\n> ").strip()

# ================= OUTPUT =================

result = translate_text(text_input, src_lang, tgt_lang)

print("\n🌍 Translated Text:\n", result)